version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:    bash -c "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty:        true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
