# Generated by Django 2.2.5 on 2019-09-09 22:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The sentiment analysis from the document service', null=True),
        ),
    ]
