# Generated by Django 2.2.5 on 2019-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='send_comms_to_customers',
            field=models.BooleanField(default=False, help_text="A flag for sending texts, emails, etc to this vendor's customers (e.g. review requests)"),
        ),
    ]
