# Generated by Django 2.2.5 on 2019-09-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='analytics_id',
            field=models.UUIDField(blank=True, help_text='The document id from the <a href="https://data-intel-documents-dev.herokuapp.com/v1">Documents Service</a>', null=True),
        ),
    ]
