# Generated by Django 2.2.5 on 2019-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_vendor_send_comms_to_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='team_id',
            field=models.CharField(default='NOT_SET', help_text='The ID of the team that owns this product', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='team_id',
            field=models.CharField(default='NOT_SET', help_text='The ID of the team that owns this vendor', max_length=255),
            preserve_default=False,
        ),
    ]
