# Generated by Django 2.2.5 on 2019-09-12 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190911_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_customer_email', models.CharField(blank=True, max_length=500, null=True)),
                ('target_customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(max_length=500)),
                ('is_thumbs_up', models.BooleanField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
