# Generated by Django 2.2.5 on 2019-09-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_reviewrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrequest',
            name='is_thumbs_up',
        ),
        migrations.RemoveField(
            model_name='reviewrequest',
            name='review_completed_at',
        ),
        migrations.RemoveField(
            model_name='reviewrequest',
            name='review_text',
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Review'),
        ),
    ]
