# Generated by Django 2.2.5 on 2019-10-23 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191004_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABSAEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(help_text='The global term (e.g. "staff")', max_length=255)),
                ('variant', models.CharField(help_text='The local variant of the term (e.g. "receptionist")', max_length=255)),
                ('start', models.PositiveIntegerField(blank=True, help_text='The start position of the variant in the text', null=True)),
                ('end', models.PositiveIntegerField(blank=True, help_text='The end position of the variant in the text', null=True)),
                ('event_type', models.CharField(choices=[('aspect', 'aspect'), ('opinion', 'opinion')], max_length=40)),
                ('score', models.FloatField(help_text='The polarity score between -1 and 1', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('team_id', models.CharField(help_text='The ID of the team that owns this event', max_length=255)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
